### ISSUE TITLE
Change language on the Android app

### ISSUE THREAD

**Issue by Kimbaras** [CalebQ42/SWAssistant#33]
Hi there!

First of all this is not an issue or a problem, it's just a request / personal preference, so feel free to close / ignore it!

I've recently started using the app on Android (Xiaomi Mi Mix 3, MIUI 12.0, Android 10 if that is of any help) and I have no problems with the usage so far. The only complaint I have is the translation.

The current Italian translation is not so great. I mean it's pretty a literal translation which results in "funny" things.
Not sure if the translation is done manually or it's an automatic thing of Android.

I'd like to use the app in English but currently the only option I got is to change the OS language, which is not really ideal.

Would it be possible to add the option to switch app language?
If not, I'll be glad to help with the proper translation for the "funny" items!

Thanks!

**Comment by CalebQ42** [comment]
That's something that I've been meaning to add, but haven't gotten around to it. If you want to help with the translation, there's a button in settings that'll take you to the app's Crowdin page.

**Comment by Kimbaras** [comment]
Ah sorry, missed it!

Thanks, will for sure give it a look!

(if want to close the issue you're free to do so :) already pleased with this option!)

**Comment by CalebQ42** [comment]
I'll keep it open so I remember to actually add it at some point

**Comment by CalebQ42** [comment]
I've added this and it will be available in the next release.
